import type { Metadata } from "next";
import "./globals.css";
import { Lora } from "next/font/google";


const lora = Lora({weight: "700", subsets:  ["latin"]})

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>
        {children}
      </body>
    </html>
  );
}
